version: '3.8'

services:
  vote:
    build:
      context: ./vote
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - redis

  result:
    build:
      context: ./result
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:5.0-alpine3.10
    ports:
      - "6379:6379"

  postgres:
    image: postgres:9.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
