name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Vérifier le code
        uses: actions/checkout@v2

      - name: Configurer Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authentifier Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: Construire et pousser les images Docker
        run: |
          docker build -t ${{ env.USERNAME }}/vote ./vote
          docker build -t ${{ env.USERNAME }}/result ./result
          docker build -t ${{ env.USERNAME }}/worker ./worker

          # Pousser les images sur Docker Hub
          docker push ${{ env.USERNAME }}/vote
          docker push ${{ env.USERNAME }}/result
          docker push ${{ env.USERNAME }}/worker
